# Generated by Django 6.1.1 on 2026-09-23 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('duration', models.PositiveIntegerField()),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed'), ('FROM', 'From'), ('NEGOTIABLE', 'Negotiable')], default='FIXED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.masterprofile')),
            ],
        ),
    ]
